name: Crawl

on:
  schedule:
    - cron: "0 16 * * 1"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crawl Apple TV catalog
        run: |
          python crawl_appletv.py

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add *.csv
          git commit --message "Update catalogs" || true

      - name: Push changes
        run: git push
